Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f8d886d5760>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5e69fcbe30>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
