Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f41c26bfbc0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd7a23bbbf0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f2e8edfc2f0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe464ec7da0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fee151c7d40>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7faa624c7c20>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6e3bac7d40>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
