Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7ff84151dbb0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
