Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f81897c6b10>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5ea02c7e60>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f77bf4c7dd0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7ffa402b07a0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
